### ISSUE TITLE
频道问题

### ISSUE THREAD

**Issue by baojinwang-rakuten** [spring2613/Daily#2]
新添加频道后，详情页未随之改变。

**Comment by Omiknight** [comment]
现在采用比较tab的哈希值来解决这个问题，如果有更好的方法欢迎交流

**Comment by gpj008** [comment]
Gradle 构建失败

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:greendao'.
> org.eclipse.jdt.internal.compiler.impl.CompilerOptions.versionToJdkLevel(Ljava/lang/Object;)J

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
