### ISSUE TITLE
Gradle 构建失败

### ISSUE THREAD

**Issue by guanpj** [spring2613/Daily#5]
java -version 1.8
buildToolsVersion '25.0.0'
com.android.tools.build:gradle:2.3.0

运行项目发现如下问题：

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:greendao'.
> org.eclipse.jdt.internal.compiler.impl.CompilerOptions.versionToJdkLevel(Ljava/lang/Object;)J

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by Omiknight** [comment]
move

classpath 'org.greenrobot:greendao-gradle-plugin:3.2.1'

form app/build.gradle into top level build.gradle file.

**Comment by guanpj** [comment]
Already being solved by this way, thx!
