### ISSUE TITLE
找不到这个类,没有提交还是忘写了?

### ISSUE THREAD

**Issue by ZhangLanqiu** [spring2613/Daily#6]
import com.cins.daily.di.component.DaggerApplicationComponent;

 // Fixme
//    private void initApplicationComponent() {
//        mApplicationComponent = DaggerApplicationComponent.builder()
//                .applicationModule(new ApplicationModule(this))
//                .build();
//    }

大约在App.java 中的165行左右

**Comment by ZhangLanqiu** [comment]
.......项目能正常运行,我有点晕了是我运行的姿势不对,可是我确实没有发现这个包下的类啊

**Comment by Omiknight** [comment]
to learn about dagger
